import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = (path) => fs.readFileSync(new URL(`../../${path}`, import.meta.url), 'utf8');

test('repository Cargo build and verification commands enforce the application lock', () => {
    let checked = 0;
    for (const path of ['launcher.sh', '.github/workflows/verify.yml']) {
        for (const line of read(path).split('\n')) {
            if (/\bcargo (build|test|check|rustc|clippy)\b/.test(line)) {
                assert.match(line, /\bcargo (build|test|check|rustc|clippy) --locked\b/, `${path}: ${line.trim()}`);
                checked += 1;
            }
        }
    }
    assert.ok(checked >= 20, 'inspect the expected repository command set');
});

test('only the root application lock is exempted from the global lock ignore', () => {
    const lines = read('.gitignore').split('\n');
    assert.ok(lines.includes('Cargo.lock'));
    assert.ok(lines.includes('!/Cargo.lock'));
    assert.ok(!lines.includes('!Cargo.lock'));
    assert.match(read('Cargo.lock'), /^# This file is automatically @generated by Cargo\./);
});

test('dependency verification consumes a committed lock without regeneration', () => {
    const workflow = read('.github/workflows/dioxus-cohort-probe.yml');
    assert.doesNotMatch(workflow, /cargo (generate-lockfile|update)\b/);
    assert.doesNotMatch(workflow, /test ! -e Cargo\.lock/);
    assert.match(workflow, /git ls-files --error-unmatch Cargo\.lock/);
    assert.match(workflow, /cmp Cargo\.lock resolution\/Cargo\.lock/);
    assert.match(workflow, /--deny warnings/);
    assert.doesNotMatch(workflow, /--ignore\b|--no-yanked\b/);
});
